// Auto-generated by fetch_logos.py
package com.pennywiseai.tracker.ui.icons

import com.pennywiseai.tracker.R

object BrandIcons {
    private val brandMappings = mapOf(
        "1mg" to R.drawable.ic_brand_1mg,
        "5paisa" to R.drawable.ic_brand_5paisa,
        "99acres" to R.drawable.ic_brand_99acres,
        "abhibus" to R.drawable.ic_brand_abhibus,
        "acko" to R.drawable.ic_brand_acko,
        "adani electricity" to R.drawable.ic_brand_adani_electricity,
        "air india" to R.drawable.ic_brand_air_india,
        "airtel" to R.drawable.ic_brand_airtel,
        "ajio" to R.drawable.ic_brand_ajio,
        "amazon" to R.drawable.ic_brand_amazon,
        "amazon pay" to R.drawable.ic_brand_amazon_pay,
        "amazon prime" to R.drawable.ic_brand_amazon_prime,
        "angel one" to R.drawable.ic_brand_angel_one,
        "anytime fitness" to R.drawable.ic_brand_anytime_fitness,
        "apollo pharmacy" to R.drawable.ic_brand_apollo_pharmacy,
        "apple music" to R.drawable.ic_brand_apple_music,
        "axis bank" to R.drawable.ic_brand_axis_bank,
        "bajaj allianz" to R.drawable.ic_brand_bajaj_allianz,
        "bandhan bank" to R.drawable.ic_brand_bandhan_bank,
        "bank of baroda" to R.drawable.ic_brand_bank_of_baroda,
        "barbeque nation" to R.drawable.ic_brand_barbeque_nation,
        "bhim" to R.drawable.ic_brand_bhim,
        "bigbasket" to R.drawable.ic_brand_bigbasket,
        "blinkit" to R.drawable.ic_brand_blinkit,
        "blu smart" to R.drawable.ic_brand_blu_smart,
        "bookmyshow" to R.drawable.ic_brand_bookmyshow,
        "bounce" to R.drawable.ic_brand_bounce,
        "bses" to R.drawable.ic_brand_bses,
        "bsnl" to R.drawable.ic_brand_bsnl,
        "burger king" to R.drawable.ic_brand_burger_king,
        "byjus" to R.drawable.ic_brand_byjus,
        "cafe coffee day" to R.drawable.ic_brand_cafe_coffee_day,
        "canara bank" to R.drawable.ic_brand_canara_bank,
        "cinepolis" to R.drawable.ic_brand_cinepolis,
        "cleartrip" to R.drawable.ic_brand_cleartrip,
        "coin" to R.drawable.ic_brand_coin,
        "coursera" to R.drawable.ic_brand_coursera,
        "cred" to R.drawable.ic_brand_cred,
        "cultfit" to R.drawable.ic_brand_cultfit,
        "curefit" to R.drawable.ic_brand_curefit,
        "dish tv" to R.drawable.ic_brand_dish_tv,
        "dmart" to R.drawable.ic_brand_dmart,
        "dominos" to R.drawable.ic_brand_dominos,
        "dream11" to R.drawable.ic_brand_dream11,
        "dunzo" to R.drawable.ic_brand_dunzo,
        "economic times" to R.drawable.ic_brand_economic_times,
        "eros now" to R.drawable.ic_brand_eros_now,
        "etmoney" to R.drawable.ic_brand_etmoney,
        "federal bank" to R.drawable.ic_brand_federal_bank,
        "firstcry" to R.drawable.ic_brand_firstcry,
        "fitternity" to R.drawable.ic_brand_fitternity,
        "flipkart" to R.drawable.ic_brand_flipkart,
        "freecharge" to R.drawable.ic_brand_freecharge,
        "gaana" to R.drawable.ic_brand_gaana,
        "goibibo" to R.drawable.ic_brand_goibibo,
        "golds gym" to R.drawable.ic_brand_golds_gym,
        "great learning" to R.drawable.ic_brand_great_learning,
        "grofers" to R.drawable.ic_brand_grofers,
        "groww" to R.drawable.ic_brand_groww,
        "haldirams" to R.drawable.ic_brand_haldirams,
        "hathway" to R.drawable.ic_brand_hathway,
        "hdfc bank" to R.drawable.ic_brand_hdfc_bank,
        "hdfc life" to R.drawable.ic_brand_hdfc_life,
        "healthifyme" to R.drawable.ic_brand_healthifyme,
        "healthkart" to R.drawable.ic_brand_healthkart,
        "hindustan times" to R.drawable.ic_brand_hindustan_times,
        "housejoy" to R.drawable.ic_brand_housejoy,
        "housingcom" to R.drawable.ic_brand_housingcom,
        "icici bank" to R.drawable.ic_brand_icici_bank,
        "icici prudential" to R.drawable.ic_brand_icici_prudential,
        "idfc first bank" to R.drawable.ic_brand_idfc_first_bank,
        "ind money" to R.drawable.ic_brand_ind_money,
        "indian express" to R.drawable.ic_brand_indian_express,
        "indigo" to R.drawable.ic_brand_indigo,
        "indusind bank" to R.drawable.ic_brand_indusind_bank,
        "inox" to R.drawable.ic_brand_inox,
        "irctc" to R.drawable.ic_brand_irctc,
        "ixigo" to R.drawable.ic_brand_ixigo,
        "jio" to R.drawable.ic_brand_jio,
        "jiomart" to R.drawable.ic_brand_jiomart,
        "jiosaavn" to R.drawable.ic_brand_jiosaavn,
        "kfc" to R.drawable.ic_brand_kfc,
        "kotak mahindra bank" to R.drawable.ic_brand_kotak_mahindra_bank,
        "kuvera" to R.drawable.ic_brand_kuvera,
        "lazypay" to R.drawable.ic_brand_lazypay,
        "lic" to R.drawable.ic_brand_lic,
        "lybrate" to R.drawable.ic_brand_lybrate,
        "magicbricks" to R.drawable.ic_brand_magicbricks,
        "makemytrip" to R.drawable.ic_brand_makemytrip,
        "max life" to R.drawable.ic_brand_max_life,
        "mcdonalds" to R.drawable.ic_brand_mcdonalds,
        "medlife" to R.drawable.ic_brand_medlife,
        "meesho" to R.drawable.ic_brand_meesho,
        "microsoft teams" to R.drawable.ic_brand_microsoft_teams,
        "mobikwik" to R.drawable.ic_brand_mobikwik,
        "mpl" to R.drawable.ic_brand_mpl,
        "mtnl" to R.drawable.ic_brand_mtnl,
        "mx player" to R.drawable.ic_brand_mx_player,
        "myntra" to R.drawable.ic_brand_myntra,
        "netflix" to R.drawable.ic_brand_netflix,
        "netmeds" to R.drawable.ic_brand_netmeds,
        "nobroker" to R.drawable.ic_brand_nobroker,
        "nykaa" to R.drawable.ic_brand_nykaa,
        "ola" to R.drawable.ic_brand_ola,
        "ola electric" to R.drawable.ic_brand_ola_electric,
        "paytm" to R.drawable.ic_brand_paytm,
        "paytm first games" to R.drawable.ic_brand_paytm_first_games,
        "paytm insider" to R.drawable.ic_brand_paytm_insider,
        "paytm money" to R.drawable.ic_brand_paytm_money,
        "pepperfry" to R.drawable.ic_brand_pepperfry,
        "pharmeasy" to R.drawable.ic_brand_pharmeasy,
        "phonepe" to R.drawable.ic_brand_phonepe,
        "pizza hut" to R.drawable.ic_brand_pizza_hut,
        "policybazaar" to R.drawable.ic_brand_policybazaar,
        "practo" to R.drawable.ic_brand_practo,
        "punjab national bank" to R.drawable.ic_brand_punjab_national_bank,
        "pvr" to R.drawable.ic_brand_pvr,
        "rapido" to R.drawable.ic_brand_rapido,
        "rbl bank" to R.drawable.ic_brand_rbl_bank,
        "redbus" to R.drawable.ic_brand_redbus,
        "sbi" to R.drawable.ic_brand_sbi,
        "sbi life" to R.drawable.ic_brand_sbi_life,
        "shopclues" to R.drawable.ic_brand_shopclues,
        "simpl" to R.drawable.ic_brand_simpl,
        "simplilearn" to R.drawable.ic_brand_simplilearn,
        "slack" to R.drawable.ic_brand_slack,
        "slice" to R.drawable.ic_brand_slice,
        "smallcase" to R.drawable.ic_brand_smallcase,
        "snapdeal" to R.drawable.ic_brand_snapdeal,
        "sony liv" to R.drawable.ic_brand_sony_liv,
        "spicejet" to R.drawable.ic_brand_spicejet,
        "spotify" to R.drawable.ic_brand_spotify,
        "starbucks" to R.drawable.ic_brand_starbucks,
        "sun direct" to R.drawable.ic_brand_sun_direct,
        "swiggy" to R.drawable.ic_brand_swiggy,
        "tata aia" to R.drawable.ic_brand_tata_aia,
        "tata power" to R.drawable.ic_brand_tata_power,
        "tata sky" to R.drawable.ic_brand_tata_sky,
        "the hindu" to R.drawable.ic_brand_the_hindu,
        "the times of india" to R.drawable.ic_brand_the_times_of_india,
        "tikona" to R.drawable.ic_brand_tikona,
        "timespoints" to R.drawable.ic_brand_timespoints,
        "toppr" to R.drawable.ic_brand_toppr,
        "truemeds" to R.drawable.ic_brand_truemeds,
        "uber" to R.drawable.ic_brand_uber,
        "udacity" to R.drawable.ic_brand_udacity,
        "udemy" to R.drawable.ic_brand_udemy,
        "unacademy" to R.drawable.ic_brand_unacademy,
        "union bank" to R.drawable.ic_brand_union_bank,
        "upgrad" to R.drawable.ic_brand_upgrad,
        "upstox" to R.drawable.ic_brand_upstox,
        "urban company" to R.drawable.ic_brand_urban_company,
        "urban ladder" to R.drawable.ic_brand_urban_ladder,
        "vedantu" to R.drawable.ic_brand_vedantu,
        "vistara" to R.drawable.ic_brand_vistara,
        "vodafone" to R.drawable.ic_brand_vodafone,
        "vodafone idea" to R.drawable.ic_brand_vodafone_idea,
        "vogo" to R.drawable.ic_brand_vogo,
        "voot" to R.drawable.ic_brand_voot,
        "whitehat jr" to R.drawable.ic_brand_whitehat_jr,
        "wynk" to R.drawable.ic_brand_wynk,
        "yatra" to R.drawable.ic_brand_yatra,
        "yes bank" to R.drawable.ic_brand_yes_bank,
        "youtube" to R.drawable.ic_brand_youtube,
        "yulu" to R.drawable.ic_brand_yulu,
        "zee5" to R.drawable.ic_brand_zee5,
        "zepto" to R.drawable.ic_brand_zepto,
        "zerodha" to R.drawable.ic_brand_zerodha,
        "zomato" to R.drawable.ic_brand_zomato,
        "zoom" to R.drawable.ic_brand_zoom,
    )
    
    fun getIconResource(merchantName: String): Int? {
        val normalized = merchantName.lowercase()
        return brandMappings.entries
            .firstOrNull { (key, _) -> normalized.contains(key) }
            ?.value
    }
    
    fun getBrandColor(merchantName: String): String? = when {
        // Entertainment
        merchantName.contains("netflix", ignoreCase = true) -> "#E50914"
        merchantName.contains("spotify", ignoreCase = true) -> "#1DB954"
        merchantName.contains("youtube", ignoreCase = true) -> "#FF0000"
        merchantName.contains("disney", ignoreCase = true) -> "#113CCF"
        merchantName.contains("sony", ignoreCase = true) -> "#000000"
        merchantName.contains("zee", ignoreCase = true) -> "#6C2E91"
        merchantName.contains("voot", ignoreCase = true) -> "#E5007E"
        
        // Food
        merchantName.contains("swiggy", ignoreCase = true) -> "#FC8019"
        merchantName.contains("zomato", ignoreCase = true) -> "#E23744"
        merchantName.contains("blinkit", ignoreCase = true) -> "#FFC800"
        merchantName.contains("zepto", ignoreCase = true) -> "#9B51E0"
        merchantName.contains("dominos", ignoreCase = true) -> "#0066B3"
        merchantName.contains("mcdonalds", ignoreCase = true) -> "#FFC600"
        merchantName.contains("kfc", ignoreCase = true) -> "#F40027"
        merchantName.contains("starbucks", ignoreCase = true) -> "#00704A"
        
        // Banks
        merchantName.contains("hdfc", ignoreCase = true) -> "#004C8F"
        merchantName.contains("icici", ignoreCase = true) -> "#F37021"
        merchantName.contains("axis", ignoreCase = true) -> "#97144D"
        merchantName.contains("sbi", ignoreCase = true) -> "#22409A"
        merchantName.contains("kotak", ignoreCase = true) -> "#EF3829"
        merchantName.contains("yes bank", ignoreCase = true) -> "#0066CC"
        merchantName.contains("idfc", ignoreCase = true) -> "#8B0000"
        merchantName.contains("indusind", ignoreCase = true) -> "#98272B"
        merchantName.contains("pnb", ignoreCase = true) -> "#0E2B5C"
        
        // Payments
        merchantName.contains("paytm", ignoreCase = true) -> "#00B9F1"
        merchantName.contains("phonepe", ignoreCase = true) -> "#5F259F"
        merchantName.contains("google pay", ignoreCase = true) -> "#4285F4"
        merchantName.contains("cred", ignoreCase = true) -> "#000000"
        merchantName.contains("amazon pay", ignoreCase = true) -> "#FF9900"
        
        // Telecom
        merchantName.contains("airtel", ignoreCase = true) -> "#E52E2D"
        merchantName.contains("jio", ignoreCase = true) -> "#2A3890"
        merchantName.contains("vodafone", ignoreCase = true) -> "#E60000"
        merchantName.contains("idea", ignoreCase = true) -> "#FDD922"
        merchantName.contains("bsnl", ignoreCase = true) -> "#0078BF"
        
        // Shopping
        merchantName.contains("amazon", ignoreCase = true) -> "#FF9900"
        merchantName.contains("flipkart", ignoreCase = true) -> "#027CD5"
        merchantName.contains("myntra", ignoreCase = true) -> "#FF3F6C"
        merchantName.contains("ajio", ignoreCase = true) -> "#2C4152"
        merchantName.contains("nykaa", ignoreCase = true) -> "#FC2779"
        merchantName.contains("meesho", ignoreCase = true) -> "#F43397"
        
        // Transportation
        merchantName.contains("uber", ignoreCase = true) -> "#000000"
        merchantName.contains("ola", ignoreCase = true) -> "#93CE25"
        merchantName.contains("rapido", ignoreCase = true) -> "#FFC800"
        merchantName.contains("irctc", ignoreCase = true) -> "#FB792B"
        
        // Investment
        merchantName.contains("groww", ignoreCase = true) -> "#00D09C"
        merchantName.contains("zerodha", ignoreCase = true) -> "#387ED1"
        merchantName.contains("upstox", ignoreCase = true) -> "#5E72E4"
        merchantName.contains("angel", ignoreCase = true) -> "#5B2D90"
        
        // Healthcare
        merchantName.contains("1mg", ignoreCase = true) -> "#FC574E"
        merchantName.contains("pharmeasy", ignoreCase = true) -> "#10847E"
        merchantName.contains("netmeds", ignoreCase = true) -> "#24AEB1"
        merchantName.contains("apollo", ignoreCase = true) -> "#0066B3"
        merchantName.contains("practo", ignoreCase = true) -> "#1EBEA5"
        
        // Fitness
        merchantName.contains("cult", ignoreCase = true) -> "#FF3278"
        merchantName.contains("gym", ignoreCase = true) -> "#F15B2A"
        
        else -> null
    }
}
